name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]
jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    env:
      MONGODB_URI: ${{secrets.MONGODB_URI}}
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Install server dependencies
        working-directory: ./server
        run: npm install
      - name: Install client dependencies
        working-directory: ./client
        run: npm install
      - name: Check style backend
        working-directory: ./server
        run: npm run lint
      - name: test backend
        working-directory: ./server
        run: npm test
      - name: Check style frontend
        working-directory: ./client
        run: npm run lint
      - name: test frontend
        working-directory: ./client
        run: echo "Pretend frontend passed React-testing-library tests"
      - name: Build front end
        working-directory: ./server
        run: npm run build:ui
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./server
          command: npm run test:e2e
          start: npm start
          wait-on: http://localhost:3001
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy app
      - if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
